name: CLI Release Please for develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      target-branch:
        description: The branch you want to dispatch the workflow
        required: false
        type: string
        default: develop
      latest-tag-sha:
        description: For any release, only consider as far back as this commit SHA
        required: false
        type: string
        default: ""
      versioning-strategy:
        description: >-
          The versioning-strategy you want to follow, [choices:
          "always-bump-major", "alway-bump-minor", "always-bump-patch",
          "default"]
        required: false
        type: string
        default: default
jobs:
  install-release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: "18"
      - name: Install release-please globally
        run: npm install release-please -g
      - name: ls
        run: ls -a

  create-release-pr:
    runs-on: ubuntu-latest
    needs: install-release-please
    steps:
      - name: Install release-please globally
        run: npm install release-please -g

      - name: Create a release PR
        run: |
          USER_INPUT=${{ github.event.inputs.versioning-strategy }}
          release-please release-pr \
            --latest-tag-name=v3.0.1 \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo-url=shriharisbhat/auto-releasing \

  create-release:
    runs-on: ubuntu-latest
    needs: create-release-pr
    steps:
      - name: Install release-please globally
        run: npm install release-please -g
      - name: Create a github release
        run: |
          release-please github-release \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo-url=shriharisbhat/auto-releasing \

        # --release-type=node \
        # --changelog-sections=feat,feature,fix,chore \
        # --versioning-strategy=${USER_INPUT:-"default"} \
