name: CLI Release Please for develop
"on":
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      target-branch:
        description: The branch you want to dispatch the workflow
        required: false
        type: string
        default: develop
      versioning-strategy:
        description: >-
          The versioning-strategy you want to follow, [choices:
          "always-bump-major", "alway-bump-minor", "always-bump-patch",
          "default"]
        required: false
        type: string
        default: "default"
jobs:
  install-release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: "18"
      - name: Install release-please globally
        run: npm install release-please -g
      - name: ls
        run: ls -a
      - name: Create a release PR
        run: |
          release-please release-pr \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo-url=shriharisbhat/auto-releasing \
            --versioning-strategy=${{ github.event.inputs.versioning-strategy }} \
            --config-file=release-please-config-temp.json
